Near-One/rainbow-bridge

environment/Dockerfile, rainbowup/main.py, rainbowup/rainbowuplib/ethrelay_service.py
This address #39 . To run it first go to enviroment/, build a docker image:
```
git submodule update --init --recursive
docker build . -t rainbow_environment
```
(optionaly image can be tagged and pushed to remote)
Then in rainbowup/ run:
```
python3 main.py run --rainbow_environment_image rainbow_environment
```
It should works exactly same as native nodejs rainbow_environment
=> Add support to run rainbow_environment in docker

.buildkite/pipeline.yml
It was follow nearcore's legacy branch pattern: master/beta/stable, that if pipeline were committed into repo, it diverge in master/beta/stable was a problem. but now rainbow-bridge only have every PR commit to master branch, and in future it probably will cut release just from master branch (same as current nearcore), so move pipeline file into repo gives benefit that PRs can modify pipeline file accordingly, such as rename enviroment -> rainbow_cli need to modify this pipeline file
=> move pipeline definition in repo

ci/e2e.sh, environment/commands/clean.js, environment/commands/prepare.js, environment/scripts/prepare.sh
In rainbow-bridge, e2e.sh should take arg so it use local nearcore. In nearcore ci, it will checkout latest bridge, and run e2e.sh with current commit nearcore
=> Parameter to run e2e test in nearcore ci

environment/commands/status.js, environment/index.js, environment/lib/near-helpers.js
First version of `node index.js status` command. Related to #257.
Answer for turned ganache/near-node on:
Answer for turned ganache/near-node off:
Known issues:
1. Not checking bytecode of deployed ETH contracts. Not sure is it possible. Marked as TODO.
2. Not checking NEAR Contracts validity because of poor and unclear access to them. Marked as TODO.
3. No eth-relay/near-relay/watchdog status.
@nearmax, @ailisp if you can help with 1 or 2 please do.
=> index.js status

environment/scripts/prepare.sh
Fix #271 
This happens about 20% of the time and only on ci. Finally figure out cause from `~/.pm2/pm2.log`:
```
2020-08-18T00:35:04: PM2 log: App [ganache:0] starting in -fork mode-
2020-08-18T00:35:04: PM2 log: App [ganache:0] online
2020-08-18T00:36:35: PM2 log: App [near-relay:1] starting in -fork mode-
2020-08-18T00:36:38: PM2 log: App [near-relay:1] online
2020-08-18T00:36:44: PM2 log: App [eth-relay:2] starting in -fork mode-
2020-08-18T00:36:47: PM2 log: App [eth-relay:2] online
2020-08-18T00:36:54: PM2 log: App [near-watchdog:3] starting in -fork mode-
2020-08-18T00:36:54: PM2 error: Trace: [Error: ENOENT: no such file or directory, open '/var/lib/buildkite-agent/.rainbow/logs/near-watchdog/out.log'] {
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: …
```
=> fix near-watchdog not start on ci

.buildkite/pipeline.yml, ci/patch_contract_version.js
As point out by @Kouprin , change in rainbow-bridge-sol and rainbow-bridge-rs should trigger ci here. The other direction is not needed because rainbow-bridge-cli use pinned version of some rainbow-bridge-sol & rainbow-bridge-rs which're already tested against cli before before published.
So the test trigger happens like this:
1. post a pr in rainbow-bridge-rs or rainbow-bridge-sol
2. contract unit tests run and pass
3. trigger integration test in rainbow-bridge-cli repo, with rainbow-bridge-sol/rs version set as commit hash of 3.
4. integration test pass and run
After 4, we can confidently merge contract repo PR, do a npm publish in contract repo, and depend on new version of contract in this cli repo.
=> patch version so contract repo changes trigger ci here

index.js, package.json, yarn.lock
Now you can init eth-client near contract with trusted-signer, default to ''. Locally i tested:
- init without trusted-signer, e2e tests behave as before
- init with `node index.js init-near-contracts --near-client-trusted-signer node0`, it can successfully submit blocks
- init with `node index.js init-near-contracts --near-client-trusted-signer someone-else`, submit blocks are rejected with error:
```
Error: {"ActionError":{"index":0,"kind":{"FunctionCallError":{"HostError":{"GuestPanic":{"panic_msg":"panicked at 'Eth-client is deployed as trust mode, only trusted_signer can add a new header', eth-client/src/lib.rs:210:13"}}}}}}
```
Note, to test locally, need to use https://github.com/near/rainbow-bridge-rs/pull/7 and https://github.com/near/rainbow-bridge-lib/pull/6 in …
=> options to init contract with trusted signer

scripts/prepare.sh
Pin the nearup version to the 0.1.2 release which is nearup v1, so we can land nearup v2 onto master.  Create a release for nearup v1: https://github.com/near/nearup/releases/tag/0.1.2 and latest version of nearup v2 which should be installed via pip once @mhalambek finishes his PR, this is just for now.
=> Pin nearup to use old v1 nearup release 0.1.2

index.js
*Resolves #365*
This is [the officially suggested solution](https://github.com/tj/commander.js/issues/48#issuecomment-49087390). I manually checked that this works for:
* global installation: `npm install -g git+https://github.com/near/rainbow-bridge-cli.git#18b9028311463396ebb5d1a8b26d8f434fac84d0`
```bash
$ npm install -g git+https://github.com/near/rainbow-bridge-cli.git#18b9028311463396ebb5d1a8b26d8f434fac84d0
$ rainbow --version
3.0.0
```
* local installation:
```bash
$ npm install git+https://github.com/near/rainbow-bridge-cli.git#18b9028311463396ebb5d1a8b26d8f434fac84d0
$ ./node_modules/.bin/rainbow --version
3.0.0
```
* local development:
```bash
$ git clone ... && cd rainbow-bridge-cli
$ npm install
$ node -- index.js --version
3.0.0
```
=> fix: rainbow --version should return the version package

cli/commands/danger-deploy-myerc20.js, cli/commands/danger-submit-invalid-near-block.js, cli/commands/near-dump.js, cli/commands/prepare.js, cli/commands/start/eth2near-relay.js, cli/commands/start/ganache.js, cli/commands/start/near.js, cli/commands/start/near2eth-relay.js, cli/commands/start/watchdog.js, cli/commands/status.js, cli/index.js, cli/init/eth-contracts.js, cli/init/near-contracts.js, cli/init/near-token-factory.js, eth2near/eth2near-block-relay/index.js, eth2near/eth2near-block-relay/package.json, near2eth/near2eth-block-relay/index.js, near2eth/near2eth-block-relay/package.json, near2eth/watchdog/index.js, testing/adapter/index.js, testing/index.js, testing/transfer-eth-erc20/deploy-token.js, testing/transfer-eth-erc20/from-near.js, testing/transfer-eth-erc20/to-near.js, utils/config/index.js, yarn.lock
=> refactor: Decouple RainbowConfig

near2eth/watchdog/index.js
When some of the blocks are not signed by all validators, bridge watchdog is unable to check the full block. Skip missing signatures.
=> fix(watchdog): Don't fail on skipped signature

README.md, cli/index.js, testing/adapter/index.js, testing/index.js
=> Update local deployment guide. Improve CLI commands.

contracts/eth/nearbridge/contracts/NearBridge.sol
* Add an explicit message if the number of block producers for the provided block is bigger than `MAX_BLOCK_PRODUCERS`
Without the message, it becomes really hard to debug if something goes wrong.
NB: as Near Testnet currently allows having >100 Validators, it makes sense to consider changing the number of `MAX_BLOCK_PRODUCERS` to something meaningful in the future (maybe 256?)
=> NearOnEthClinet: add message for BP num limit

contracts/near/eth-client/src/lib.rs, contracts/near/eth-client/src/tests.rs
Hello Guys!!
I fixed a 1 million bounty bug 😂😂
This is a fix for a bug that happens on the epoch headers.
before this fix, the epoch headers was validated with the new validator set but this makes the validation fails on some epochs (1750200, 11693400, 12819400).
you can see [here](https://github.com/binance-chain/bsc/blob/master/consensus/parlia/parlia.go#L553) that they use the previous snapshot to validate the new header.
=> fix a bug validate the epoch header using the previous validator set

contracts/near/eth-client/src/tests.rs
Hola @karim-en !
I fixed BSC tests #666 .
Description: the tests fail because we reach the limit allowed logs `HostError(NumberOfLogsExceeded { limit: 100 }`, now we can test and validate only 10 blocks (before 50 blocks). I also removed a duplicate test.
=> BSC fix tests: #666

eth2near/ethashproof/cmd/relayer/main.go
=> fix: typo in relayer/main.go

contracts/near/eth-client/src/lib.rs
This rule doesn't produce any useful impact as we don't suppose to run the light-client from the genesis block. Meantime, the rule is dangerous from the security point of view as it relies on further validation in other parts of the code.
Related #672.
=> BSC client: remove zero block trust

contracts/eth/nearbridge/test/NearBridge.js, contracts/eth/nearbridge/test/NearBridge2.js
I'd want to disable those tests as they are no longer used and working after nearcore 1.23.0 updated. The motivation for not removing those tests completely: when the new tests (updated ones) are added, it will be easier to review and verify that those will be actually the same tests but with different input data.
=> CI: disable old tests prior to nearcore 1.23.0.

contracts/near/eth-client/src/lib.rs, contracts/near/eth-client/src/tests.rs
The final epoch block was removed because after the last changes, to get the current validators set we retrieve the epoch blocks from the canonical chain instead of the final epoch property.
=> BSC: remove final epoch header

eth2near/eth2near-block-relay/index.js
The relayer uses `pub fn last_block_number` to get the last submitted block, but this logic doesn't work for BSC client because it returns the last final block and this led to getting the error `Header is already known. Number` on submitting blocks.
In this pull request, we check if the block has already been submitted before submitting it.
=> BSC: fix error `Header is already known`

contracts/eth/nearbridge/contracts/AdminControlled.sol, contracts/eth/nearbridge/test/NearBridge3.js, contracts/eth/nearprover/test/NearProver.js
* `AdminControlled`: Add explicit methods to change admin:
- `nominateAdmin()`
- `acceptAdmin()`
- `rejectNominatedAdmin()`
* `AdminControlled`: It's impossible to nominate zero-address as an admin
* `AdminControlled`: add tests for missed methods.
* `AdminControlled`: add tests for explicit methods to change admin.
=> `AdminControlled`: add explicit methods to change admin. Add tests

cli/commands/start/near2eth-relay.js, cli/index.js, near2eth/near2eth-block-relay/index.js, testing/ci/e2e.sh, testing/ci/e2e_deploy_contract.sh, testing/ci/test_challenge.sh, testing/ci/test_ethrelay_catchup.sh
The purpose of this PR is to speed up CI tests which are unnecessarily slow. This was especially crucial for some complex tests (e.g. watchdog challenge test) which sometimes are timed out having usual parameters. After these changes tests are speeded up 4-10 times. 
Changes:
* Near2Eth-relay: added `near2eth-relay-after-submit-delay-ms` parameter.
* CI tests: specify reasonable block replace duration for `NearOnEthClient` which is aligned with the lock duration.
* CI tests: set lower value for `near2eth-relay-after-submit-delay-ms` parameter which is aligned with lock & replace duration values.
* CI tests: specify reasonable value for `near2eth-relay-max-delay`.
* CI tests: minor verbosity improvements.
=> Near2Eth-relay improvements. CI tests improvements

contracts/eth/nearbridge/contracts/AdminControlled.sol, contracts/eth/nearbridge/test/NearBridge3.js
* allow only nominated admin to accept the ownership over the contract;
* this guarantees the nominated admin has control over his private key by the time of changing ownership of the contract.
Fixes #741
=> AdminControlled: ownership transfer improvements

contracts/eth/nearbridge/contracts/AdminControlled.sol
Currently, `AdminControlled` contract uses `transfer()` method to transfer ether in `adminSendEth()` method. Even though this method is not utilized at the moment, it's recommended to change it for the future as `transfer()` gas provided might change.
* Use `.call{value: amount}("")` pattern to transfer ether.
* Reentrancy is being handled because the method is having `adminOnly` modifier.
Fixes #744
=> AdminControlled: use `call` pattern to send ether

cli/commands/danger-submit-invalid-near-block.js, cli/commands/start/near2eth-relay.js, cli/index.js, docs/development.md, near2eth/near2eth-block-relay/index.js, testing/ci/e2e.sh, testing/ci/e2e_deploy_contract.sh, testing/ci/test_challenge.sh, testing/ci/test_ethrelay_catchup.sh, utils/robust.js
- Added documentation for newcomers to get started developing NEAR2Eth-Relay.
- Added CLI argument `near2eth-relay-select-duration` that sets the number of seconds to select the optimal block to submit.
- Added CLI argument `eth-use-eip-1559` which allows submitting transactions using the EIP-1559 way.
- Added a state inside the main loop to hold the block during the optimal block selection algorithm.
- Implemented delay calculation for optimal block selection.
- RobustWeb3 is extended with `maxPriorityFeePerGas` and `getFeeData` methods.
Debugging was done locally on the Hardhat Network and remotely on the Rinkeby testnet. The results can be seen on Etherscan: [0xbabe69df0d9ca729a546fc2f8823660d3d641855](https://rinkeby.etherscan.io/address/0xbabe69df0d9ca729a546fc2f8823660d3d641855). …
=> NEAR2Eth-Relay: Optimized Block Selection

cli/commands/start/near.js
When `nearcore` v1.28 was recently introduced, we got some errors in CI. These were due to the removal of `testnet` alias for `testnet` option in `neard` command as was described in that [issue](https://github.com/near/nearcore/pull/7033).
This PR fixes to use `localnet` option instead of `testnet`.
=> CI: fixes for `nearcore` v1.28.

eth2near/contract_wrapper/src/contract_wrapper_trait.rs, eth2near/contract_wrapper/src/dao_contract.rs, eth2near/contract_wrapper/src/dao_eth_client_contract.rs, eth2near/contract_wrapper/src/dao_types.rs, eth2near/contract_wrapper/src/eth_client_contract.rs, eth2near/contract_wrapper/src/eth_client_contract_trait.rs, eth2near/contract_wrapper/src/lib.rs, eth2near/contract_wrapper/src/near_contract_wrapper.rs, eth2near/eth2near-block-relay-rs/src/config.rs, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth2near-block-relay-rs/src/main.rs
Implementation of Eth Client Wrapper for interaction with DAO.
We created a trait for Eth Client Wrapper with two implementations: (1) direct interaction with contract(eth_client_contract.rs), (2) submitting the light client updates by DAO (**dao_eth_client_contract.rs**).
In DAO ETH2 Client wrapper implementation, all functions except `send_light_client_update` work in the same way as in the classic implementation and call the correspondent functions in EthClientContract inside.  In `send_light_client_update` we submit the light client update to DAO and actively wait for when the transaction will be handled on DAO (until the status changes from `InProgress`).
=> Eth2-to-Near-relay: interaction with DAO

eth2near/contract_wrapper/src/contract_wrapper_trait.rs, eth2near/contract_wrapper/src/dao_contract.rs, eth2near/contract_wrapper/src/dao_eth_client_contract.rs, eth2near/contract_wrapper/src/near_contract_wrapper.rs, eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
* Return error on sending light client update proposal if it already has been submitted.
* Increase the gas to execute the light client update proposal from 250 to 270.
* Apply cargo fmt
=> Eth2-to-Near-relay: fix sending light client update

eth2near/contract_wrapper/src/dao_eth_client_contract.rs, eth2near/contract_wrapper/src/errors.rs, eth2near/contract_wrapper/src/eth_client_contract.rs, eth2near/contract_wrapper/src/lib.rs, eth2near/contract_wrapper/src/near_contract_wrapper.rs, eth2near/eth2near-block-relay-rs/Cargo.lock, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/config.rs, eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs, eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs, eth2near/eth2near-block-relay-rs/src/init_contract.rs, eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs, eth2near/eth2near-block-relay-rs/src/lib.rs, eth2near/eth2near-block-relay-rs/src/main.rs, eth2near/eth2near-block-relay-rs/src/near_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/relay_errors.rs, eth2near/eth2near-block-relay-rs/src/test_utils.rs
* handle submission of zero headers
* timeout on submission headers to NEAR
* move timeout for fetching beacon states/blocks into configs
* check that Beacon/ETH1/NEAR networks are sync
* check config input format
* submit only finalized blocks mode
* sleep between loops iterations
* use correct sync committee between periods for signature verification
* don't subtract u64 
* find signature slot with enough sync committee bits sum
* check attestations.len > 0
* change beacon API for new one
=> Eth2-to-Near-relay: improvements and bugs fixes

eth2near/eth2near-block-relay-rs/Cargo.lock, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/init_contract.rs, eth2near/eth2near-block-relay-rs/src/lib.rs, eth2near/eth2near-block-relay-rs/src/light_client_snapshot_with_proof.rs, eth2near/eth2near-block-relay-rs/src/main.rs, eth2near/eth2near-block-relay-rs/src/test_utils.rs
Fetch the current sync committee from `eth/v1/beacon/light_client/bootstrap` instead of fetching it from the previous period of a light client update.
=> Eth2-to-Near-relay: improve init of Eth2 client contract

eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth2near-block-relay-rs/src/prometheus_metrics.rs
https://github.com/aurora-is-near/rainbow-bridge/issues/822
=> Eth2Near-relay: add extra metrics to Prometheus

eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
* Bug fix: the last slot on NEAR can contain no blocks, and in this case, "get_block_number_for_slot" returns an error, and the relay will hang up.
=> Eth2-to-Near-relay: fix bug on relayer hanging up because of RPC result

eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
> send_hand_made_light_client_update() may be liable to stall if the attested slot lands on a skip slot with another 31 skip slots following this.
> The following lines https://github.com/aurora-is-near/rainbow-bridge/blob/9f66471a11a384d325d520e0f24a59ed8d74235d/eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs#L469-L493
> The issue will be if in get_attesed_slot() the value attested_slot is a skip slow followed by 31 more skip slots. The call to get_non_empty_beacon_block_header(attested_slot)? will error and this error will be propagated.
> 
> Since last_finalized_slot_on_near is never updated we will always hit this error in send_hand_made_light_client_update().
=> Eth2-to-Near-relay: remove limits for search non empty beacon block header

eth2near/eth2near-block-relay-rs/Cargo.lock, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs, eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs, eth2near/eth2near-block-relay-rs/src/init_contract.rs, eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs, eth2near/eth2near-block-relay-rs/src/lib.rs, eth2near/eth2near-block-relay-rs/src/test_utils.rs
We should submit the light client update once in a few epoch to the Eth2 Light Client on Near. 
First, for fetching Light Client Update from Eth2 we used the following API: "eth/v1/beacon/light_client/updates", which fetched the best Light Client Update for specified period. But we faced the problem: the finality block in such Light Client Update did not updated such often as we wanted to. Some time "best" Light Client Update could stay the same for the whole period. 
So we start to use API:  "eth/v1/beacon/light_client/finality_update/", which returns the LightClientUpdate with the last finality block. Unfortunatly such LightClientUpdate does not contain the next sync committee.
Luckily, the next sync committee changing only once per period. So, for fixed this problem we start use the …
=> Eth2-to-Near-relay: fix `LightClientUpdate` for new period

eth2near/Cargo.toml, eth2near/contract_wrapper/Cargo.toml, eth2near/eth2-contract-init/Cargo.toml, eth2near/eth2-contract-init/src/init_contract.rs, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth_rpc_client/Cargo.toml, eth2near/eth_rpc_client/src/beacon_rpc_client.rs, eth2near/eth_rpc_client/src/utils.rs, eth2near/finality-update-verify/Cargo.toml
* Get the light client update for last finality slot instead the some slot in current period during initialization
* Add workspace for eth2near relay
=> Eth2Near-relay: fix the contract initialization

eth2near/contract_wrapper/src/utils.rs
Fix `SuccessValue` in the `FinalExecutionStatus` is decoded twice because the macro `#[serde(with = "base64_format"` has been added in `near-sdk = "4.1.1"`
=> Eth2Near-relayer: fix decoding success status

eth2near/contract_wrapper/src/dao_contract.rs, eth2near/eth2-contract-init/src/init_contract.rs, eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs, eth2near/eth_rpc_client/src/beacon_rpc_client.rs
Fix handling the case when the gap between NEAR and Ethereum is more than one period. Send the update for the next period, not for the last one.
=> Eth2Near-relayer: fix sending update for the next period

.github/workflows/e2e.yml, utils/scripts/prepare.sh
- Replace `self-hosted` with `ubuntu-latest` to fix the error related to the introduced ipv6 in the [near core  1.32.0](https://github.com/near/nearcore/blob/1.32.0/chain/network/src/tcp.rs#L65)  `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" }', chain/network/src/tcp.rs:186:48`
- Revert `utils/scripts/prepare.sh` changes.
=> CI: Use the latest `nearcore` version

eth2near/contract_wrapper/Cargo.toml, eth2near/contract_wrapper/rust-toolchain, eth2near/contract_wrapper/src/dao_eth_client_contract.rs, eth2near/contract_wrapper/src/eth_client_contract.rs, eth2near/contract_wrapper/src/eth_client_contract_trait.rs, eth2near/contract_wrapper/src/file_eth_client_contract.rs, eth2near/contract_wrapper/src/lib.rs, eth2near/eth2-contract-init/Cargo.toml, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth2near-block-relay-rs/src/test_utils.rs
The `workspaces` is a heavy crate used just for tests, so it shouldn't be compiled in release apps.
In this PR:
- Hide the sandbox wrapper code under the feature flag.
- Apply cargo fmt to the `contract_wrapper` crate
=> Contract wrapper: move some crates to `dev-dependencies`

contracts/near/eth-types/Cargo.toml
Downgrade the `sha3` dependency to fix versions conflicts
=> Downgrade sha3 version

eth2near/Cargo.lock, eth2near/eth2near-block-relay-rs/Cargo.toml, eth2near/eth_rpc_client/Cargo.toml
Remove `thread` crate to fix the Eth2Near relayer build
=> Fix Eth2Near relayer build

cli/index.js, testing/ci/e2e.sh, testing/ci/e2e_deploy_contract.sh, testing/ci/test_challenge.sh, testing/ci/test_ethrelay_catchup.sh, testing/ci/test_npm_package.sh
A new restriction to the accounts naming has been added in the near core here https://github.com/near/nearcore/pull/9658
=> Fix e2e tests

contracts/near/eth2-utility/src/consensus.rs
Updated the light client config for mainnet based on the specs 
https://github.com/ethereum/consensus-specs/blob/87d4fbdcc4e6a15b1218119b4cbcc59430f52a6b/configs/mainnet.yaml#L54
=> Eth2Client: update mainnet config

contracts/near/Cargo.lock, contracts/near/Cargo.toml, contracts/near/eth2-client/Cargo.toml, contracts/near/eth2-client/src/lib.rs, eth2near/Cargo.lock, eth2near/Cargo.toml
- Replaced `bls::AggregateSignature::fast_aggregate_verify` with NEAR host functions:
- `env::bls12381_map_fp2_to_g2` for G2 mapping
- `env::bls12381_p1_decompress`/`env::bls12381_p2_decompress` for point decompression
- `env::bls12381_p1_sum` for public key aggregation
- `env::bls12381_pairing_check` for final signature verification
- Added AMCL dependency for `hash_to_field_fp2` operation
- Removed BLS crate dependency
- Updated NEAR SDK to 5.13.0
The new implementation:
1. Hashes message to FP2 field elements using XMD:SHA-256_SSWU_RO_POP
2. Maps FP2 elements to G2 points
3. Decompresses and aggregates public keys into single G1 point
4. Performs pairing check: e(pk_agg, msg_g2) = e(G1, sig)
This maintains identical verification semantics while leveraging NEAR's optimized host …
=> Switch BLS signature verification to use native host functions
