environment/index.js
environment/lib/eth-proof-extractor/index.js
environment/lib/eth-prover-tester/index.js

For any web3 ws connection, it needs manually close otherwise nodejs will wait it close before exit and stuck

Fix web3 stuck

---

environment/commands/clean/index.js
environment/commands/init-near-test-contracts/index.js
environment/commands/start/eth-relay.js
environment/commands/start/ganache.js
environment/commands/start/helpers.js
environment/commands/start/index.js
environment/commands/start/near.js
environment/index.js
environment/lib/eth-client-setup/index.js
environment/lib/eth-relay/index.js
environment/lib/eth-relay/start.js
environment/package-lock.json
environment/scripts/prepare.sh

Summary:
Implemented the start command.
Test Plan:
Need help with this. cc: @nearmax @ailisp 
Not sure how to test this i tried:
```
node index.js start --near-master-account node0 --near-master-sk ed25519:3D4YudUQRE39Lc4JHghuB5WM8kbgDDa34mnrEP5DdTApVH81af7e2dWgNPEaiQfdJnZq1CNPp5im4Rg5b733oiMP
```
but eth-relay fails with:
```
Failed to fetch state of the node0 account. Is it initialized?
```
in 
```
async accountExists (accountId) {                                           
110         const account = new nearlib.Account(this.near.connection, accountId);   
111         try {                                                                   
112             await account.fetchState();                                         
113             return true; …
```

First version of the start command

---

environment/commands/clean/index.js
environment/commands/prepare/index.js
environment/commands/start/eth-relay.js
environment/commands/start/ganache.js
environment/commands/start/helpers.js
environment/index.js
environment/scripts/prepare.sh

Fixes #73 and #74

---

libs-sol/nearbridge/package.json
libs-sol/nearbridge/test/NearBridge2.js
libs-sol/nearbridge/test/ed25519-test-cases.json
libs-sol/nearbridge/test/ed25519-test.js
libs-sol/nearbridge/yarn.lock

fixes #113 
Question: how to add it to the CI pipeline? 
@nearmax @ailisp

ED25519 test cases added

---

README.md

show master build badge

---

Dockerfile
README.md
config.json
docker-compose-dev.yml
environment/commands/clean.js
environment/commands/start/eth-relay.js
environment/commands/start/ganache.js
environment/commands/start/near-relay.js
environment/commands/start/near-watchdog.js
environment/commands/start/near.js
environment/commands/stop/near.js
environment/lib/config.js
environment/package.json
environment/scripts/prepare.sh

Only rename rainbowup to rainbow for less confliction resolve

---

environment/index.js
environment/lib/near2eth-watchdog.js
environment/lib/robust.js
environment/package.json
environment/yarn.lock

Address #207 
Figured out a way to manually construct txn and use same amount of gas as the web3 contract.methods.method.send.

watchdog retry with 2x gas

---

environment/lib/borsh/index.js
environment/lib/eth2near-relay.js

```
39|eth-relay  | 2020-07-30 16:13:53.089: Client block number is 7952
39|eth-relay  | 2020-07-30 16:13:53.093: Chain block number is 8253
39|eth-relay  | 2020-07-30 16:13:56.548: Got and parsed block 7953 to block 7962
39|eth-relay  | 2020-07-30 16:13:56.549: Submitting block 7953 to EthClient
39|eth-relay  | 2020-07-30 16:13:56.616: TxHash FQY9XWr2V7Zazn36Nr4QHvM2naSvYA571YNwy2uwtogk
39|eth-relay  | 2020-07-30 16:13:56.617: Submitting block 7954 to EthClient
39|eth-relay  | 2020-07-30 16:13:56.665: TxHash DuLLgbGkR7FbeiDbbUQkEkw1yy2Vqct3NZXwshhdekke
39|eth-relay  | 2020-07-30 16:13:56.665: Submitting block 7955 to EthClient
39|eth-relay  | 2020-07-30 16:13:56.706: TxHash F8H4XVUffooQYXVbTMFgtbsCyVJEDMbb1axwkFTuxAcZ
39|eth-relay  | 2020-07-30 16:13:56.707: Submitting block 7956 to …
```

Eth relay catchup

---

libs-sol/token-locker/contracts/TokenLocker.sol

Use the safeTransfer pattern consistently

---

ci/test_challenge.sh
environment/commands/start/near2eth-watchdog.js
environment/commands/status.js
environment/index.js

Fixes https://github.com/near/rainbow-bridge/issues/257.

Status ext

---

.gitignore
README.md
cli/commands/clean.js
cli/commands/prepare.js
cli/commands/start/near.js
cli/commands/stop/process.js
cli/index.js
utils/scripts/prepare.sh

Instead of pulling nearup from git
use latest version from pip.

Upgrade nearup to latest version

---

cli/index.js
eth2near/eth2near-block-relay/eth-proof-extractor.js
eth2near/eth2near-block-relay/index.js
testing/adapter/index.js
testing/ci/e2e.sh
testing/ci/e2e_deploy_contract.sh
testing/ci/test_challenge.sh
testing/ci/test_ethrelay_catchup.sh
testing/ci/test_npm_package.sh
testing/index.js
testing/transfer-eth-erc20/from-near.js
testing/transfer-eth-erc20/to-near.js
utils/index.js

- revisit adapter methods
- add adapter methods for approve and lock eth-to-near txs
- expose token name in adapter methods
- add eth-to-near-find-proof method to CLI
- move transfer commands to testing CLI explicitly

feat(cli, adapter): update CLI and adapter

---

cli/index.js
testing/adapter/index.js
testing/index.js
utils/borshify-proof.js

- get-client-block-height-hash for getting the latest block available on client;
- near-to-eth-unlock to unlock tokens

feat(adapter): near-to-eth methods + minor upds

---

cli/commands/start/eth2near-relay.js
cli/commands/start/near2eth-relay.js
cli/index.js
eth2near/eth2near-block-relay/index.js
eth2near/eth2near-block-relay/package.json
near2eth/near2eth-block-relay/index.js
near2eth/near2eth-block-relay/package.json
utils/http-prometheus.js
yarn.lock

Collect basic metrics and server
them via http server for Promethues to scrape.
closes near/near-ops#275

Promethues metrics from relayers

---

cli/commands/start/address-watcher.js
cli/commands/start/eth2near-relay.js
cli/commands/start/watchdog.js
cli/index.js
cli/init/eth-contracts.js
cli/init/near-contracts.js
cli/package.json
docs/address-watcher.md
eth2near/eth2near-block-relay/eth-on-near-client.js
eth2near/eth2near-block-relay/eth-proof-extractor.js
eth2near/eth2near-block-relay/index.js
near2eth/near2eth-block-relay/index.js
near2eth/watchdog/index.js
utils/address-watcher.js
utils/helpers.js
utils/http-prometheus.js
utils/robust.js
yarn.lock

Several features are added in this PR, since this is the code used to run in production for each bridge. It probably makes sense before merging to split it in several commits and review them independently.

Update relayers to work in production

---

cli/commands/clean.js
cli/commands/prepare.js
cli/commands/start/near.js
cli/commands/stop/process.js
cli/index.js
testing/transfer-eth-erc20/to-near.js
utils/scripts/prepare.sh
yarn.lock

fix: Use nearup for local testing

---

utils/scripts/clean_start.sh
utils/scripts/prepare.sh

Also add script for starting everything localy.

Download neard from s3 instead of building it

---

contracts/near/Cargo.lock
contracts/near/Cargo.toml
contracts/near/admin-controlled/Cargo.toml
contracts/near/admin-controlled/src/lib.rs
contracts/near/eth-client/Cargo.toml
contracts/near/eth-client/src/lib.rs
contracts/near/eth-prover/Cargo.toml
contracts/near/eth-prover/src/lib.rs

Test plan
=======
- (TODO): Near contracts are compiled deterministically
- (TODO): Unit test that stress pause conditions
- e2e pass

Add option to pause Near contracts

---

contracts/near/eth-client/Cargo.toml
contracts/near/eth-client/src/lib.rs

EthClient: fix tests.

---

contracts/eth/nearprover/Makefile
contracts/eth/nearprover/hardhat.config.js
contracts/eth/nearprover/package.json
contracts/eth/nearprover/utils/upgrade_admin.js
contracts/eth/nearprover/yarn.lock

* Implement get slots command
* Implement upgrade admin command

Generic admin upgrade.

---

.github/workflows/contracts-eth.yml
.github/workflows/contracts-near.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml
.github/workflows/tests.yml
cli/commands/start/near.js
testing/ci/test_ethrelay_catchup.sh
testing/vendor/ganache/package.json
testing/vendor/ganache/yarn.lock

Several things done there:
1. Logs of all components are printed to UI
2. Fixed ganache compatibility issue
3. Increased ganache block production speed `12` -> `1`
4. Better cleanup
5. Minor workflow syntax fixes

Tune e2e CI

---

contracts/eth/nearprover/UPGRADE.md
contracts/eth/nearprover/utils/upgrade_admin.js
contracts/eth/nearprover/utils/utils.js

* Ignore case for admin address
* Log the mask and selected slot content
* Update README

Upgrade admin: minor improvements

---

near2eth/near2eth-block-relay/index.js
utils/robust.js

Improve import `lodash` package

Fix import loadash package

---

contracts/near/eth-client/src/lib.rs
contracts/near/eth-client/src/tests.rs

* Minor refactoring and fixes
* Stylistic fixes

BSC: minor refactoring and fixes

---

contracts/eth/nearbridge/hardhat.config.js
contracts/eth/nearbridge/package.json
contracts/eth/nearbridge/yarn.lock
contracts/eth/nearprover/hardhat.config.js

* Hardhat: use Solidity v0.8.11 for compiling contracts.
* `NearBridge`: Add hardhat-gas-reporter.

Hardhat: use Solidity v0.8.11. Add gas reporter

---

contracts/eth/nearprover/package.json
contracts/eth/nearprover/test/NearProver.js
contracts/eth/nearprover/test/proof7.json
contracts/eth/nearprover/yarn.lock
utils/borshify-proof.js

* Apply the fixes of `borshifyOutcomeProof` from https://github.com/aurora-is-near/rainbow-bridge-client/commit/555c3c4ee471e6593f29b1b05edb69ed6ea8ccbf
* Remove deprecated `rainbow-bridge-lib` dependency

Fix: NEAR proof sharding fix.

---

eth2near/contract_wrapper/src/near_contract_wrapper.rs
eth2near/eth2near-block-relay-rs/src/beacon_block_body_merkle_tree.rs
eth2near/eth2near-block-relay-rs/src/beacon_block_header_with_execution_data.rs
eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
eth2near/eth2near-block-relay-rs/src/config.rs
eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
eth2near/eth2near-block-relay-rs/src/init_contract.rs
eth2near/eth2near-block-relay-rs/src/lib.rs
eth2near/eth2near-block-relay-rs/src/logger.rs
eth2near/eth2near-block-relay-rs/src/main.rs

* Fixes #770.
* Minor improvements and fixes.
* Formatting fixes.

Eth2-to-Near-relay: minor improvements and fixes

---

.github/workflows/contracts-eth.yml
.github/workflows/contracts-near.yml
.github/workflows/e2e.yml
.github/workflows/lint.yml

* Add `the-merge` branch to GitHub workflows

CI: enable workflows on `the-merge` branch

---

eth2near/contract_wrapper/src/contract_wrapper_trait.rs
eth2near/contract_wrapper/src/dao_contract.rs
eth2near/contract_wrapper/src/dao_types.rs
eth2near/contract_wrapper/src/eth_client_contract.rs
eth2near/contract_wrapper/src/lib.rs
eth2near/contract_wrapper/src/near_contract_wrapper.rs

Implement a wrapper for Sputnik DAO contract.
* Added the needed DAO APIs 
* Minor code improvements and apply fmt
More details about the DAO are here 
https://github.com/near-daos/sputnik-dao-contract

Eth2-to-Near-relay: add DAO contract interface

---

eth2near/contract_wrapper/src/dao_contract.rs
eth2near/contract_wrapper/src/dao_types.rs

* Fix `add_proposal`
* Improve submit update description
* Add all available types of `ProposalKind`
* Fix  parsing `Proposal.vote_counts`

Eth2-to-Near-relay: DAO contract interface fixes

---

eth2near/contract_wrapper/src/dao_contract.rs
eth2near/contract_wrapper/src/eth_client_contract.rs
eth2near/contract_wrapper/src/near_contract_wrapper.rs
eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
eth2near/eth2near-block-relay-rs/src/relay_errors.rs

Issue: https://github.com/aurora-is-near/rainbow-bridge/issues/815

Eth2-to-Near-relay: remove some asserts and imrpove error handling

---

eth2near/contract_wrapper/src/contract_wrapper_trait.rs
eth2near/contract_wrapper/src/dao_contract.rs
eth2near/contract_wrapper/src/dao_eth_client_contract.rs
eth2near/contract_wrapper/src/eth_client_contract.rs
eth2near/contract_wrapper/src/eth_client_contract_trait.rs
eth2near/contract_wrapper/src/file_eth_client_contract.rs
eth2near/contract_wrapper/src/near_contract_wrapper.rs
eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs

https://github.com/aurora-is-near/rainbow-bridge/issues/805

`contract-wrapper`: improve documentation

---

cli/commands/start/eth2near-relay.js
cli/commands/status.js
cli/commands/update-dag-merkle-roots.js
cli/init/near-contracts.js
cli/init/near-token-factory.js
eth2near/eth2near-block-relay/eth-on-near-client.js
eth2near/eth2near-block-relay/index.js
near2eth/near2eth-block-relay/index.js
testing/adapter/index.js
testing/ci/e2e.sh
testing/ci/test_ethrelay_catchup.sh
testing/transfer-eth-erc20/deploy-token.js
testing/transfer-eth-erc20/from-near.js
testing/transfer-eth-erc20/to-near.js
utils/address-watcher.js
utils/borsh.js
utils/helpers.js
utils/package.json
utils/robust.js
utils/utils.js
yarn.lock

* Update `near-api-js` package to v1.1.0.
* Set `near2eth-relay-block-select-duration` to 0.

CI: fix E2E tests

---

eth2near/eth2-contract-init/src/config.rs
eth2near/eth2-contract-init/src/init_contract.rs
eth2near/eth2near-block-relay-rs/Cargo.toml
eth2near/eth2near-block-relay-rs/src/config.rs
eth2near/eth2near-block-relay-rs/src/contract_type.rs
eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
eth2near/eth2near-block-relay-rs/src/main.rs
eth2near/eth2near-block-relay-rs/src/test_utils.rs
eth2near/eth_rpc_client/Cargo.toml
eth2near/eth_rpc_client/src/beacon_rpc_client.rs
eth2near/eth_rpc_client/src/execution_block_proof.rs
eth2near/eth_rpc_client/src/hand_made_finality_light_client_update.rs

- Fix beacon rpc route
- Fix network type

Eth2Near: minor bug fixes

---

contracts/near/eth-client/.catalog-info.yaml

chore(backstage): client-eth2.bridge.near address
